Repository kintoproj/kinto-helm, pull requests merged in 2021-03, with the labels that each got.

#15 🚧 Allow to disable SSL
  README.md
  templates/cert-manager-secret.yaml
  templates/common-ssl-issuer.yaml
  templates/common-wildcard-certificate.yaml
  templates/core-certificate.yaml
  templates/core-deployment.yaml
  templates/core-ingress.yaml
  templates/dashboard-certificate.yaml
  templates/dashboard-ingress.yaml
  values.yaml
Labels: enhancement

#24 🚧 Improve kintohub deployment
  .helmignore
  Chart.yaml
  README.md
  templates/common-wildcard-certificate.yaml
  templates/core-certificate.yaml
  templates/core-deployment.yaml
  templates/core-ingress.yaml
  templates/dashboard-certificate.yaml
  templates/dashboard-deployment.yaml
  templates/dashboard-ingress.yaml
  values.yaml
Labels: enhancement

#27 🚧 Added NOTES.txt information
  Chart.yaml
  README.md
  templates/NOTES.txt
Labels: documentation

#29 🚧 Allow Kinto to pull images from external repo
  Chart.yaml
  templates/NOTES.txt
  templates/core-deployment.yaml
Labels: enhancement

#28 🌟 feat: use tag instead of latest image
  Chart.yaml
  values.yaml
Labels: enhancement

#30 🐛 Fix Cronjob resume on builder
  Chart.yaml
  values.yaml
Labels: bug

#31 🚧 Add helm lint on pr to main
  .github/workflows/helm-lint.yaml
  README.md
  charts/kinto/.gitignore
  charts/kinto/.helmignore
  charts/kinto/Chart.lock
  charts/kinto/Chart.yaml
  charts/kinto/templates/NOTES.txt
  charts/kinto/templates/_helpers.tpl
  charts/kinto/templates/builder-cluster-role-binding.yaml
  charts/kinto/templates/builder-cluster-role.yaml
  charts/kinto/templates/builder-deployment.yaml
  charts/kinto/templates/builder-service-account.yaml
  charts/kinto/templates/builder-service.yaml
  charts/kinto/templates/builder-workflow-cluster-role-binding.yaml
  charts/kinto/templates/builder-workflow-cluster-role.yaml
  charts/kinto/templates/builder-workflow-docker-secret.yaml
  charts/kinto/templates/builder-workflow-service-account.yaml
  charts/kinto/templates/cert-manager-secret.yaml
  charts/kinto/templates/common-ssl-issuer.yaml
  charts/kinto/templates/common-wildcard-certificate.yaml
  charts/kinto/templates/core-certificate.yaml
  charts/kinto/templates/core-cluster-role-binding.yaml
  charts/kinto/templates/core-cluster-role.yaml
  charts/kinto/templates/core-deployment.yaml
  charts/kinto/templates/core-ingress.yaml
  charts/kinto/templates/core-service-account.yaml
  charts/kinto/templates/core-service.yaml
  charts/kinto/templates/dashboard-certificate.yaml
  charts/kinto/templates/dashboard-deployment.yaml
  charts/kinto/templates/dashboard-ingress.yaml
  charts/kinto/templates/dashboard-service.yaml
  charts/kinto/values.yaml
  charts/minio-5.0.32.tgz
  charts/nginx-ingress-controller-5.3.24.tgz
  charts/proxless-0.2.0.tgz
  ct.yaml
Labels: enhancement

#32 🚧 Feat/automatic chart package
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  README.md
Labels: enhancement

#33 🚧 Improve deployment doc
  README.md
  charts/kinto/Chart.yaml
  charts/kinto/templates/NOTES.txt
  charts/kinto/values.yaml
Labels: documentation

#35 🚧 Add default empty dir on workflow
  charts/kinto/Chart.yaml
  charts/kinto/values.yaml
Labels: bug

#36 🚧 Add kinto core secret
  README.md
  charts/kinto/Chart.yaml
  charts/kinto/templates/builder-deployment.yaml
  charts/kinto/templates/core-deployment.yaml
  charts/kinto/values.yaml
Labels: DO_NOT_MERGE

#37 🚧 Add a production values file
  README.md
  charts/kinto/Chart.yaml
  charts/kinto/templates/NOTES.txt
  charts/kinto/values-prod.yaml
  charts/kinto/values.yaml
Labels: enhancement

#38 🚧 Add k8s secret for kinto core secret
  charts/kinto/Chart.yaml
  charts/kinto/templates/core-deployment.yaml
  charts/kinto/templates/core-secret.yaml
  charts/kinto/values-prod.yaml
  charts/kinto/values.yaml
Labels: enhancement
