Repository kintoproj/kinto-helm, pull requests merged in 2021-02, with the labels that each got.

#6 Some minor enhancement on the README
  README.md
Labels: DO_NOT_MERGE

#4 🚧 Improve install documentation
  README.md
  charts/proxless-0.2.0.tgz
  requirements.lock
  requirements.yaml
  templates/_helpers.tpl
  templates/builder-deployment.yaml
  templates/cert-manager-secret.yaml
  templates/common-ssl-issuer.yaml
  templates/common-wildcard-certificate.yaml
  templates/core-certificate.yaml
  templates/core-deployment.yaml
  templates/dashboard-certificate.yaml
  templates/dashboard-deployment.yaml
  templates/dashboard-ingress.yaml
  templates/dashboard-service.yaml
  templates/frontend-ingress.yaml
  values.yaml
Labels: documentation, enhancement

#11 🚀 Helm 3 chart
  Chart.lock
  Chart.yaml
  charts/argo-0.9.5.tgz
  charts/cert-manager-v0.15.0.tgz
  charts/proxless-0.2.0.tgz
  requirements.lock
  requirements.yaml
  templates/common-networkpolicy.yaml
  values.yaml
  vendored_charts/proxless/Chart.yaml
  vendored_charts/proxless/README.md
  vendored_charts/proxless/charts/redis-10.5.7.tgz
  vendored_charts/proxless/requirements.lock
  vendored_charts/proxless/requirements.yaml
  vendored_charts/proxless/templates/_helpers.tpl
  vendored_charts/proxless/templates/clusterrole.yaml
  vendored_charts/proxless/templates/deployment.yaml
  vendored_charts/proxless/templates/ingress.yaml
  vendored_charts/proxless/templates/role.yaml
  vendored_charts/proxless/templates/service.yaml
  vendored_charts/proxless/templates/serviceaccount.yaml
  vendored_charts/proxless/values.yaml
Labels: enhancement

#12 🐛 Fix update env
  Chart.yaml
  templates/core-cluster-role.yaml
Labels: bug
